FROM mcr.microsoft.com/devcontainers/typescript-node:0-18

# RUN apt-get update && sudo apt-get upgrade && export DEBIAN_FRONTEND=noninteractive \
    # && apt-get -y install git apache2-utils

EXPOSE 5000